### ISSUE TITLE
No Options button

### ISSUE THREAD

**Issue by JReally** [bbbbbr/thunderbird-secure-addressing#3] opened 2018-12-21 22:08 UTC
I tried the release for Thunderbird 60.4... t seemed to install OK but there was no Options button

**Comment by bbbbbr** [comment] 2018-12-22 14:15
For the time being you can find the Add-on's preferences in the same location as the previous author's extension:
* Tools -> Add on Preferences -> Secure Addressing 60

I will look into enabling the options button in the Add-on panel

**Comment by JReally** [comment] 2018-12-22 15:36
found it. (that's a new option on this version of Thunderbird). Once people find their way aroun the new Thunderbird it won't be necessary to add the options button.

All the settings were correct (based upon the previous version of secure addressing) but address lookup doesn't happen.  I must be missing something

**Comment by bbbbbr** [comment] 2018-12-22 18:06
Can you be more specific about address lookup not happening? 

Do you mean when entering a recipient in the address bar of an email compose window? What is the expected behavior?

There are some features of this add-on which I don't use, and so am not familiar and haven't validated on Tbird 60. (Such as customized auto completion, internal/external domains and address cleanup)

**Comment by JReally** [comment] 2018-12-22 18:41
Typically i would enter the first few characters of an address an it would auto complete.
If I disable the custom auto complete option, I get the TBird lists but it lists adrsses from all my address books.
If I enable the custom auto complete option, I have to type the whole address

So it's the auto complete option that is not working... it's a feature I really wanted.
With secure addressing auto complete only a sub-set of addresses would be used

**Comment by bbbbbr** [comment] 2018-12-22 21:15
I think I understand, though I'll have to figure out where the problem is and the best way to test it. I do not see it working here either, though I don't have a good reference for when it does work.

Did you see that the original extension author has recently published v1.90 that supports Tbird 60 on the official Mozilla page on Dec 1? Does that one resolve the problem you are seeing? 

I would not expect my version to have any benefit compared with their new build at this time.

**Comment by JReally** [comment] 2018-12-22 22:04
1.9 works as I described so it looks like Hiroya is still maintaining the app
Thanks for your efforts tho'
Perhaps you could coordinate with Hiroya about future updates?

**Comment by bbbbbr** [comment] 2018-12-25 05:41
Merged in the 1.9 code updates from the original author.

**Closed as completed by bbbbbr** 2018-12-25 05:41 UTC
